# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170429_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/images/avatars/', verbose_name='profile picture'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/images/avatars/', verbose_name='profile picture'),
        ),
    ]
