# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170429_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Complete Adress', max_length=30),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Complete Adress', max_length=30),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Required. Format: YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Required. Format: YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='disease',
            field=models.TextField(blank=True, help_text='What Disease You have?', max_length=500),
        ),
    ]
