# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170430_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='disease',
            field=models.TextField(blank=True, help_text='What Disease You have?', max_length=50),
        ),
    ]
