# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170501_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/media/profile_imgs/default.png', null=True, upload_to='static/media/profile_imgs', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, default='Nothing in Bio, Please edit your Profile in Settings', max_length=500),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/media/profile_imgs/default.png', null=True, upload_to='static/media/profile_imgs', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='disease',
            field=models.TextField(blank=True, default='No Disease', help_text='What Disease You have?', max_length=100),
        ),
    ]
